use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

use anyhow::Result;
use but_hooks::managed_hooks::{
    HookSetupOutcome, ensure_managed_hooks, install_managed_hooks, install_managed_hooks_enabled,
    set_install_managed_hooks_enabled,
};

use super::{create_repo_with_hooks_dir, create_user_hook, hook_exists, read_hook};

#[test]
fn installs_when_no_manager_and_config_default() -> Result<()> {
    let (_temp, repo, hooks_dir) = create_repo_with_hooks_dir()?;

    let outcome = ensure_managed_hooks(&repo, &hooks_dir, false);
    assert!(
        matches!(outcome, HookSetupOutcome::Installed),
        "Should install hooks on clean repo, got: {outcome:?}"
    );

    assert!(hook_exists(&hooks_dir, "pre-commit"));
    assert!(hook_exists(&hooks_dir, "post-checkout"));
    assert!(hook_exists(&hooks_dir, "pre-push"));
    Ok(())
}

#[test]
fn returns_disabled_by_config() -> Result<()> {
    let (_temp, repo, hooks_dir) = create_repo_with_hooks_dir()?;

    set_install_managed_hooks_enabled(&repo, false)?;
    // Re-open to pick up the config change.
    let repo = gix::open(_temp.path())?;

    let outcome = ensure_managed_hooks(&repo, &hooks_dir, false);
    assert!(
        matches!(outcome, HookSetupOutcome::DisabledByConfig),
        "Should return DisabledByConfig when config is false, got: {outcome:?}"
    );

    // No hooks should be installed.
    assert!(!hook_exists(&hooks_dir, "pre-commit"));
    assert!(!hook_exists(&hooks_dir, "post-checkout"));
    assert!(!hook_exists(&hooks_dir, "pre-push"));
    Ok(())
}

#[test]
fn force_bypasses_disabled_config() -> Result<()> {
    let (_temp, repo, hooks_dir) = create_repo_with_hooks_dir()?;

    set_install_managed_hooks_enabled(&repo, false)?;
    // Re-open to pick up the config change.
    let repo = gix::open(_temp.path())?;

    let outcome = ensure_managed_hooks(&repo, &hooks_dir, true);
    assert!(
        matches!(outcome, HookSetupOutcome::Installed),
        "force=true should bypass DisabledByConfig, got: {outcome:?}"
    );

    assert!(hook_exists(&hooks_dir, "pre-commit"));
    assert!(hook_exists(&hooks_dir, "post-checkout"));
    assert!(hook_exists(&hooks_dir, "pre-push"));
    Ok(())
}

#[test]
fn detects_prek_and_persists_config() -> Result<()> {
    let (_temp, repo, hooks_dir) = create_repo_with_hooks_dir()?;

    // Create a prek-managed hook.
    let prek_hook = "#!/bin/sh\n# File generated by prek\nexec prek hook-impl pre-commit\n";
    create_user_hook(&hooks_dir, "pre-commit", prek_hook)?;

    // Also create a prek.toml in workdir so the manager is detected.
    fs::write(_temp.path().join("prek.toml"), "# prek config\n")?;

    let outcome = ensure_managed_hooks(&repo, &hooks_dir, false);
    assert!(
        matches!(
            outcome,
            HookSetupOutcome::ExternalManagerDetected {
                ref manager_name,
                ..
            } if manager_name == "prek"
        ),
        "Should detect prek, got: {outcome:?}"
    );

    // Config should be persisted as false.
    let repo = gix::open(_temp.path())?;
    assert!(
        !install_managed_hooks_enabled(&repo),
        "installHooks should be persisted as false after detection"
    );
    Ok(())
}

#[test]
fn subsequent_call_after_detection_returns_disabled() -> Result<()> {
    let (_temp, repo, hooks_dir) = create_repo_with_hooks_dir()?;

    // Create a prek-managed hook + config.
    let prek_hook = "#!/bin/sh\n# File generated by prek\nexec prek hook-impl pre-commit\n";
    create_user_hook(&hooks_dir, "pre-commit", prek_hook)?;
    fs::write(_temp.path().join("prek.toml"), "# prek config\n")?;

    // First call: detect manager.
    let outcome1 = ensure_managed_hooks(&repo, &hooks_dir, false);
    assert!(matches!(
        outcome1,
        HookSetupOutcome::ExternalManagerDetected { .. }
    ));

    // Re-open repo to see persisted config.
    let repo = gix::open(_temp.path())?;

    // Second call: should hit DisabledByConfig fast path.
    let outcome2 = ensure_managed_hooks(&repo, &hooks_dir, false);
    assert!(
        matches!(outcome2, HookSetupOutcome::DisabledByConfig),
        "Subsequent call should return DisabledByConfig, got: {outcome2:?}"
    );
    Ok(())
}

#[test]
fn force_overrides_external_manager() -> Result<()> {
    let (_temp, repo, hooks_dir) = create_repo_with_hooks_dir()?;

    // Create a prek-managed hook + config.
    let prek_hook = "#!/bin/sh\n# File generated by prek\nexec prek hook-impl pre-commit\n";
    create_user_hook(&hooks_dir, "pre-commit", prek_hook)?;
    fs::write(_temp.path().join("prek.toml"), "# prek config\n")?;

    // Force install should skip detection and install hooks.
    let outcome = ensure_managed_hooks(&repo, &hooks_dir, true);
    assert!(
        matches!(outcome, HookSetupOutcome::Installed),
        "force=true should override external manager, got: {outcome:?}"
    );

    // Prek hook should be backed up, GB hook installed.
    assert!(hook_exists(&hooks_dir, "pre-commit-user"));
    let content = read_hook(&hooks_dir, "pre-commit")?;
    assert!(
        content.contains("GITBUTLER_MANAGED_HOOK_V1"),
        "GitButler hook should be installed after force"
    );
    Ok(())
}

#[test]
fn detection_cleans_up_existing_gb_hooks() -> Result<()> {
    let (_temp, repo, hooks_dir) = create_repo_with_hooks_dir()?;

    // Pre-install GitButler hooks (simulates prior app-triggered install).
    install_managed_hooks(&hooks_dir, false)?;
    assert!(hook_exists(&hooks_dir, "pre-commit"));
    assert!(hook_exists(&hooks_dir, "post-checkout"));
    assert!(hook_exists(&hooks_dir, "pre-push"));

    // Now introduce a prek-managed hook (overwriting GB's pre-commit).
    let prek_hook = "#!/bin/sh\n# File generated by prek\nexec prek hook-impl pre-commit\n";
    fs::write(hooks_dir.join("pre-commit"), prek_hook)?;
    fs::write(_temp.path().join("prek.toml"), "# prek config\n")?;

    let outcome = ensure_managed_hooks(&repo, &hooks_dir, false);
    assert!(matches!(
        outcome,
        HookSetupOutcome::ExternalManagerDetected { .. }
    ));

    // GB-managed post-checkout and pre-push should be cleaned up.
    assert!(
        !hook_exists(&hooks_dir, "post-checkout"),
        "post-checkout should be removed after external manager detection"
    );
    assert!(
        !hook_exists(&hooks_dir, "pre-push"),
        "pre-push should be removed after external manager detection"
    );

    // The prek hook should still be there (uninstall only removes GB-managed hooks).
    let content = read_hook(&hooks_dir, "pre-commit")?;
    assert!(
        content.contains("File generated by prek"),
        "Prek hook should not be removed"
    );
    Ok(())
}

#[test]
fn skips_unknown_external_hook() -> Result<()> {
    let (_temp, repo, hooks_dir) = create_repo_with_hooks_dir()?;

    // Create an unknown external hook (not a known manager, no config files).
    let unknown_hook = "#!/bin/sh\n# Some unknown hook manager\necho 'unknown'\n";
    create_user_hook(&hooks_dir, "pre-commit", unknown_hook)?;

    let outcome = ensure_managed_hooks(&repo, &hooks_dir, false);
    assert!(
        matches!(
            outcome,
            HookSetupOutcome::HookSkipped { ref hook_name } if hook_name == "pre-commit"
        ) || matches!(outcome, HookSetupOutcome::Installed),
        "Should either skip unknown hook or install remaining, got: {outcome:?}"
    );

    // The unknown hook should be preserved.
    let content = read_hook(&hooks_dir, "pre-commit")?;
    assert_eq!(
        content, unknown_hook,
        "Unknown external hook should be preserved"
    );
    Ok(())
}

#[test]
fn idempotent_on_installed_hooks() -> Result<()> {
    let (_temp, repo, hooks_dir) = create_repo_with_hooks_dir()?;

    // First install.
    let outcome1 = ensure_managed_hooks(&repo, &hooks_dir, false);
    assert!(matches!(outcome1, HookSetupOutcome::Installed));

    // Second install — should still return Installed (already configured).
    let outcome2 = ensure_managed_hooks(&repo, &hooks_dir, false);
    assert!(
        matches!(outcome2, HookSetupOutcome::Installed),
        "Idempotent call should return Installed, got: {outcome2:?}"
    );
    Ok(())
}

/// Verify that `HookSetupOutcome::PartialSuccess` is returned (not `Installed`) when
/// hook writes fail due to an IO error, and that warnings are surfaced to the caller.
///
/// Uses a read-only hooks directory so every `fs::write` inside `install_hook` fails,
/// causing all three hooks to collect errors rather than returning success or skipped.
#[cfg(unix)]
#[test]
fn partial_success_surfaces_warnings() -> Result<()> {
    let (_temp, repo, hooks_dir) = create_repo_with_hooks_dir()?;

    // Make the hooks directory read-only so all hook file writes fail with EACCES.
    fs::set_permissions(&hooks_dir, fs::Permissions::from_mode(0o555))?;

    let outcome = ensure_managed_hooks(&repo, &hooks_dir, false);

    // Restore so TempDir cleanup can remove the directory.
    fs::set_permissions(&hooks_dir, fs::Permissions::from_mode(0o755))?;

    match outcome {
        HookSetupOutcome::PartialSuccess { ref warnings } => {
            assert!(
                !warnings.is_empty(),
                "PartialSuccess should carry at least one warning, got none"
            );
        }
        other => panic!("Expected PartialSuccess, got: {other:?}"),
    }

    Ok(())
}
